### ISSUE TITLE
Font tidak sesuai dengan web sebelumnya

### ISSUE THREAD

**Issue by mrandika** [mrandika/indonet-web-prototype#2]
Gunakan **Montserrat** sebagai font. Implementasikan dengan menambahkan 
`<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">`, dan pada `style-infrastructure.css` panggil dengan cara 
```
body {
    font-family: 'Montserrat', sans-serif;
}
```
Kuy lah ! 👍

**Comment by aqli1107** [comment]
udah sob
sanskuy la m8 😭
