### ISSUE TITLE
Jenis font tidak sesuai

### ISSUE THREAD

**Issue by mrandika** [mrandika/indonet-web-prototype#6]
Ubah `Montserrat` menjadi `Open Sans`.
dengan menambah/mengganti line Google Font seperti berikut : 
`<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">`
lalu, jangan lupa untuk mengganti font family di `style-infrastructure.css`.

**Comment by aqli1107** [comment]
udeh
